//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from formula_grammar.g by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="formula_grammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
//[System.CLSCompliant(false)]
public interface Iformula_grammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] formula_grammarParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] formula_grammarParser.IdentifierContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegation([NotNull] formula_grammarParser.NegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.negation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegation([NotNull] formula_grammarParser.NegationContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_string_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThe_string_type([NotNull] formula_grammarParser.The_string_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_string_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThe_string_type([NotNull] formula_grammarParser.The_string_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjunction([NotNull] formula_grammarParser.DisjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjunction([NotNull] formula_grammarParser.DisjunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.predicateTuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicateTuple([NotNull] formula_grammarParser.PredicateTupleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.predicateTuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicateTuple([NotNull] formula_grammarParser.PredicateTupleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_boolean_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThe_boolean_type([NotNull] formula_grammarParser.The_boolean_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_boolean_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThe_boolean_type([NotNull] formula_grammarParser.The_boolean_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_int_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThe_int_type([NotNull] formula_grammarParser.The_int_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_int_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThe_int_type([NotNull] formula_grammarParser.The_int_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] formula_grammarParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] formula_grammarParser.PredicateContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] formula_grammarParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] formula_grammarParser.ConditionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] formula_grammarParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] formula_grammarParser.ConjunctionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.variable_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_term([NotNull] formula_grammarParser.Variable_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.variable_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_term([NotNull] formula_grammarParser.Variable_termContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.literal_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral_term([NotNull] formula_grammarParser.Literal_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.literal_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral_term([NotNull] formula_grammarParser.Literal_termContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormula([NotNull] formula_grammarParser.FormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormula([NotNull] formula_grammarParser.FormulaContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_char_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThe_char_type([NotNull] formula_grammarParser.The_char_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_char_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThe_char_type([NotNull] formula_grammarParser.The_char_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_float_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThe_float_type([NotNull] formula_grammarParser.The_float_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_float_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThe_float_type([NotNull] formula_grammarParser.The_float_typeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] formula_grammarParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] formula_grammarParser.TermContext context);
}
