//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from formula_grammar.g by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="Iformula_grammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class formula_grammarBaseListener : Iformula_grammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] formula_grammarParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] formula_grammarParser.IdentifierContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegation([NotNull] formula_grammarParser.NegationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.negation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegation([NotNull] formula_grammarParser.NegationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_string_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThe_string_type([NotNull] formula_grammarParser.The_string_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_string_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThe_string_type([NotNull] formula_grammarParser.The_string_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.disjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisjunction([NotNull] formula_grammarParser.DisjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.disjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisjunction([NotNull] formula_grammarParser.DisjunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.predicateTuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicateTuple([NotNull] formula_grammarParser.PredicateTupleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.predicateTuple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicateTuple([NotNull] formula_grammarParser.PredicateTupleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_boolean_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThe_boolean_type([NotNull] formula_grammarParser.The_boolean_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_boolean_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThe_boolean_type([NotNull] formula_grammarParser.The_boolean_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_int_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThe_int_type([NotNull] formula_grammarParser.The_int_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_int_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThe_int_type([NotNull] formula_grammarParser.The_int_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredicate([NotNull] formula_grammarParser.PredicateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.predicate"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredicate([NotNull] formula_grammarParser.PredicateContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] formula_grammarParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] formula_grammarParser.ConditionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConjunction([NotNull] formula_grammarParser.ConjunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.conjunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConjunction([NotNull] formula_grammarParser.ConjunctionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.variable_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_term([NotNull] formula_grammarParser.Variable_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.variable_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_term([NotNull] formula_grammarParser.Variable_termContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.literal_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_term([NotNull] formula_grammarParser.Literal_termContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.literal_term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_term([NotNull] formula_grammarParser.Literal_termContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormula([NotNull] formula_grammarParser.FormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormula([NotNull] formula_grammarParser.FormulaContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_char_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThe_char_type([NotNull] formula_grammarParser.The_char_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_char_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThe_char_type([NotNull] formula_grammarParser.The_char_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.the_float_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThe_float_type([NotNull] formula_grammarParser.The_float_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.the_float_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThe_float_type([NotNull] formula_grammarParser.The_float_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="formula_grammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] formula_grammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="formula_grammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] formula_grammarParser.TermContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
